### Checkout
POST http://localhost:8080/checkout


### Usage API
GET http://localhost:8080/api?apiKey=b815411bda3e7578e8b54778ab0d76aa

### Customer Usage
GET http://localhost:8080/usage/cus_LCm9AohkiFlCex

